language: node_js
node_js:
  - 8.0.0
sudo: required
services:
  - docker
before_install:
  - docker-compose up --build -d
  - sleep 100
  - docker exec -it traviscqlshtest_redis_1 /mount/redis/create.sh
  - docker exec -it traviscqlshtest_redis_1 /mount/redis/retrieve.sh
  - docker exec -it traviscqlshtest_cassandra_1 /mount/cassandra/create-keyspace.sh
  - docker exec -it traviscqlshtest_cassandra_1 /mount/cassandra/create-table.sh
  - docker exec -it traviscqlshtest_cassandra_1 /mount/cassandra/create.sh
  - docker exec -it traviscqlshtest_cassandra_1 /mount/cassandra/retrieve.sh
  - docker exec -it traviscqlshtest_kafka_1 /mount/kafka/create-topics.sh
  - docker exec -it traviscqlshtest_kafka_1 /mount/kafka/produce.sh
  - docker exec -it traviscqlshtest_kafka_1 /mount/kafka/consume.sh
script:
  - chmod +x ./components/create-multiplexer.sh
  - ./components/create-multiplexer.sh
  - npm test